//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity2_Rbac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserGroups
    {
        public int ApplicationUserId { get; set; }
        public int ApplicationGroupId { get; set; }
    
        public virtual ApplicationGroups ApplicationGroups { get; set; }
    }
}
